{{if eq .Values.gateway true}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "deploy-chart.fullname" . }}-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "deploy-chart.fullname" . }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ include "deploy-chart.fullname" . }}-gateway
  http:
  - match:
    - uri:
        prefix: /ret/
    route:
    - destination:
        host: {{ include "deploy-chart.fullname" . }}      
{{end}}