apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: http-mock
build:
  artifacts:
  - image: http-mock-image
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yaml
portForward:
- resourceType: service
  resourceName: http-mock
  port: 8080
