# Default values for deploy-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

gateway: false

image:
  repository: gcr.io  
  name: python-flask-test  
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
